-- AlterTable
ALTER TABLE "Car" ALTER COLUMN "brake" DROP NOT NULL,
ALTER COLUMN "date" DROP NOT NULL,
ALTER COLUMN "driver_number" DROP NOT NULL,
ALTER COLUMN "drs" DROP NOT NULL,
ALTER COLUMN "meeting_key" DROP NOT NULL,
ALTER COLUMN "n_gear" DROP NOT NULL,
ALTER COLUMN "rpm" DROP NOT NULL,
ALTER COLUMN "session_key" DROP NOT NULL,
ALTER COLUMN "speed" DROP NOT NULL,
ALTER COLUMN "throttle" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Drivers" ALTER COLUMN "broadcast_name" DROP NOT NULL,
ALTER COLUMN "country_code" DROP NOT NULL,
ALTER COLUMN "driver_number" DROP NOT NULL,
ALTER COLUMN "first_name" DROP NOT NULL,
ALTER COLUMN "full_name" DROP NOT NULL,
ALTER COLUMN "headshot_url" DROP NOT NULL,
ALTER COLUMN "last_name" DROP NOT NULL,
ALTER COLUMN "meeting_key" DROP NOT NULL,
ALTER COLUMN "name_acronym" DROP NOT NULL,
ALTER COLUMN "session_key" DROP NOT NULL,
ALTER COLUMN "team_colour" DROP NOT NULL,
ALTER COLUMN "team_name" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Interval" ALTER COLUMN "date" DROP NOT NULL,
ALTER COLUMN "driver_number" DROP NOT NULL,
ALTER COLUMN "meeting_key" DROP NOT NULL,
ALTER COLUMN "session_key" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Laps" ALTER COLUMN "date_start" DROP NOT NULL,
ALTER COLUMN "driver_number" DROP NOT NULL,
ALTER COLUMN "duration_sector_1" DROP NOT NULL,
ALTER COLUMN "duration_sector_2" DROP NOT NULL,
ALTER COLUMN "duration_sector_3" DROP NOT NULL,
ALTER COLUMN "i1_speed" DROP NOT NULL,
ALTER COLUMN "i2_speed" DROP NOT NULL,
ALTER COLUMN "is_pit_out_lap" DROP NOT NULL,
ALTER COLUMN "lap_duration" DROP NOT NULL,
ALTER COLUMN "lap_number" DROP NOT NULL,
ALTER COLUMN "meeting_key" DROP NOT NULL,
ALTER COLUMN "session_key" DROP NOT NULL,
ALTER COLUMN "st_speed" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Location" ALTER COLUMN "date" DROP NOT NULL,
ALTER COLUMN "driver_number" DROP NOT NULL,
ALTER COLUMN "meeting_key" DROP NOT NULL,
ALTER COLUMN "session_key" DROP NOT NULL,
ALTER COLUMN "x" DROP NOT NULL,
ALTER COLUMN "y" DROP NOT NULL,
ALTER COLUMN "z" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Meetings" ALTER COLUMN "circuit_key" DROP NOT NULL,
ALTER COLUMN "circuit_short_name" DROP NOT NULL,
ALTER COLUMN "country_code" DROP NOT NULL,
ALTER COLUMN "country_key" DROP NOT NULL,
ALTER COLUMN "country_name" DROP NOT NULL,
ALTER COLUMN "date_start" DROP NOT NULL,
ALTER COLUMN "gmt_offset" DROP NOT NULL,
ALTER COLUMN "location" DROP NOT NULL,
ALTER COLUMN "meeting_key" DROP NOT NULL,
ALTER COLUMN "meeting_name" DROP NOT NULL,
ALTER COLUMN "meeting_official_name" DROP NOT NULL,
ALTER COLUMN "year" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Pit" ALTER COLUMN "date" DROP NOT NULL,
ALTER COLUMN "driver_number" DROP NOT NULL,
ALTER COLUMN "lap_number" DROP NOT NULL,
ALTER COLUMN "meeting_key" DROP NOT NULL,
ALTER COLUMN "pit_duration" DROP NOT NULL,
ALTER COLUMN "session_key" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Position" ALTER COLUMN "date" DROP NOT NULL,
ALTER COLUMN "driver_number" DROP NOT NULL,
ALTER COLUMN "meeting_key" DROP NOT NULL,
ALTER COLUMN "position" DROP NOT NULL,
ALTER COLUMN "session_key" DROP NOT NULL;

-- AlterTable
ALTER TABLE "RaceControl" ALTER COLUMN "category" DROP NOT NULL,
ALTER COLUMN "date" DROP NOT NULL,
ALTER COLUMN "meeting_key" DROP NOT NULL,
ALTER COLUMN "message" DROP NOT NULL,
ALTER COLUMN "session_key" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Sessions" ALTER COLUMN "circuit_key" DROP NOT NULL,
ALTER COLUMN "circuit_short_name" DROP NOT NULL,
ALTER COLUMN "country_code" DROP NOT NULL,
ALTER COLUMN "country_key" DROP NOT NULL,
ALTER COLUMN "country_name" DROP NOT NULL,
ALTER COLUMN "date_end" DROP NOT NULL,
ALTER COLUMN "date_start" DROP NOT NULL,
ALTER COLUMN "gmt_offset" DROP NOT NULL,
ALTER COLUMN "location" DROP NOT NULL,
ALTER COLUMN "meeting_key" DROP NOT NULL,
ALTER COLUMN "session_key" DROP NOT NULL,
ALTER COLUMN "session_name" DROP NOT NULL,
ALTER COLUMN "session_type" DROP NOT NULL,
ALTER COLUMN "year" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Stints" ALTER COLUMN "compound" DROP NOT NULL,
ALTER COLUMN "driver_number" DROP NOT NULL,
ALTER COLUMN "lap_end" DROP NOT NULL,
ALTER COLUMN "lap_start" DROP NOT NULL,
ALTER COLUMN "meeting_key" DROP NOT NULL,
ALTER COLUMN "session_key" DROP NOT NULL,
ALTER COLUMN "stint_number" DROP NOT NULL,
ALTER COLUMN "tyre_age_at_start" DROP NOT NULL;

-- AlterTable
ALTER TABLE "TeamRadio" ALTER COLUMN "date" DROP NOT NULL,
ALTER COLUMN "driver_number" DROP NOT NULL,
ALTER COLUMN "meeting_key" DROP NOT NULL,
ALTER COLUMN "recording_url" DROP NOT NULL,
ALTER COLUMN "session_key" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Weather" ALTER COLUMN "air_temperature" DROP NOT NULL,
ALTER COLUMN "date" DROP NOT NULL,
ALTER COLUMN "humidity" DROP NOT NULL,
ALTER COLUMN "meeting_key" DROP NOT NULL,
ALTER COLUMN "pressure" DROP NOT NULL,
ALTER COLUMN "rainfall" DROP NOT NULL,
ALTER COLUMN "session_key" DROP NOT NULL,
ALTER COLUMN "track_temperature" DROP NOT NULL,
ALTER COLUMN "wind_direction" DROP NOT NULL,
ALTER COLUMN "wind_speed" DROP NOT NULL;
